#!/bin/sh
#查找当前目录下存在此"字符串"的文件 - 行, 高亮显示
#Usage: findf 'string'
#Author: jingwentian

if [ $# -lt 1 ]; then
    echo "find in file:  $name"
    exit 1
fi
string=$1
#grep -rn "$string" ./ | grep -v \.svn
#grep -rn "$string" ./ | grep -v \.svn | grep -v \.git | grep -v \log
grep -rn --color "$string" ./ --exclude-dir='.git' --exclude-dir='.svn' --exclude-dir='logs' --exclude='.gitconfig' --exclude='.bash_history' --exclude='templates_c'
